  sys.exit(start_ipython())
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
      return launch_new_instance(argv=argv, **kwargs)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
      app.start()
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
      self.shell.mainloop()
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
      self.interact()
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 555, in interact
      self.run_cell(code, store_history=True)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2877, in run_cell
      result = self._run_cell(
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2923, in _run_cell
      return runner(coro)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3146, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3338, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/n/sw/eb/apps/centos7/Anaconda3/2020.11/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-77-4acf1573d68f>", line 13, in <module>
      history = model.fit(X_train,y_train,epochs=50, batch_size=16, validation_data=(X_valid, y_valid),
    File "/n/home07/uchadaya/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/n/home07/uchadaya/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/n/home07/uchadaya/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/n/home07/uchadaya/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/n/home07/uchadaya/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "/n/home07/uchadaya/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1027, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/n/home07/uchadaya/.local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 526, in minimize
      grads_and_vars = self.compute_gradients(loss, var_list, tape)
    File "/n/home07/uchadaya/.local/lib/python3.8/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 259, in compute_gradients
      grads = tape.gradient(loss, var_list)
Node: 'gradient_tape/U-Net/batch_normalization_233/FusedBatchNormGradV3'
OOM when allocating tensor with shape[16,64,512,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node gradient_tape/U-Net/batch_normalization_233/FusedBatchNormGradV3}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_100736]